# Generated by Django 4.2.6 on 2024-11-25 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'delegations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'jurisdictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'states',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('localisation', models.CharField(max_length=500)),
                ('date_posted', models.DateField()),
                ('phone', models.IntegerField()),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.delegation')),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.jurisdiction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.state')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'annonces',
            },
        ),
    ]
