# Generated by Django 4.2.6 on 2024-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='localisation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
