# Generated by Django 4.2.6 on 2024-11-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_alter_annonce_localisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
