# Generated by Django 4.2.6 on 2024-11-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_is_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='is_processed',
        ),
    ]
