# Generated by Django 3.2.17 on 2025-01-19 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0004_remove_annonce_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.delegation'),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.jurisdiction'),
        ),
    ]
