# Generated by Django 5.1.5 on 2025-01-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0005_auto_20250119_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='id_folder',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
