# Generated by Django 5.1.5 on 2025-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_annonce_id_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
