# Generated by Django 5.1.5 on 2025-04-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_alter_annonce_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
