# Generated by Django 5.1.5 on 2025-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_alter_annonce_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='url',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
