BEGIN;

CREATE TABLE IF NOT EXISTS types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL
);

INSERT INTO types (id, name) VALUES
(1, 'Colocations'),
(2, 'Maisons et Villas'),
(3, 'Magasins, Commerces et Locaux industriels'),
(4, 'Locations de vacances'),
(5, 'Appartements'),
(6, 'Bureaux et Plateaux'),
(7, 'Autres Immobiliers'),
(8, 'Terrains et Fermes');

COMMIT;
