# Generated by Django 3.2.17 on 2025-03-12 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_alter_annonce_title'),
        ('users', '0004_remove_user_city_remove_user_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annonces.state'),
        ),
    ]
