# Generated by Django 5.0.4 on 2025-12-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='updated_by',
        ),
    ]
