# Generated by Django 5.0.4 on 2025-12-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_replied_at_complaint_replied_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='description',
            new_name='Text',
        ),
    ]
