# Generated by Django 5.0.4 on 2025-12-01 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_rename_description_complaint_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='replied_by',
        ),
    ]
