# Generated by Django 4.2.6 on 2024-11-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=100)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce')),
            ],
            options={
                'db_table': 'images',
            },
        ),
    ]
