# Generated by Django 5.1.5 on 2025-02-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_alter_annonce_title'),
        ('images', '0002_alter_image_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='annonce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce'),
        ),
    ]
