# Generated by Django 5.0.4 on 2025-12-01 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0009_annonce_url'),
        ('feedback', '0002_alter_feedback_activity_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='activity_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comping_centre_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='anounce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='annonces.annonce'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.CharField(blank=True, default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
