# Generated by Django 5.0.4 on 2025-12-01 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_remove_feedback_activity_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='anounce',
            new_name='annonce',
        ),
    ]
