# Generated by Django 5.0.4 on 2025-12-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_rename_anounce_feedback_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='description',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
